apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  eureka.client.register-with-eureka: "true"
  eureka.client.fetch-registry: "true"
  eureka.client.service-url.defaultzone: "http://eureka-server:8761/eureka"
  eureka.instance.prefer-ip-address: "true"
  server.shutdown: "graceful"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.show-sql: "true"

