apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: haribhuvan/app:payment_ms
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: spring.application.name
          value: payment-service
        - name: server.port
          value: "8084"
        - name: spring.datasource.url
          value: jdbc:mysql://mysql-svc:3306/payment_service
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: password
        - name: razorpay.key.id
          value: #razor-pay-id
        - name: razorpay.key.secret
          value: #razor-pay-secret
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  type: ClusterIP


