apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: haribhuvan/app:product_ms
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: spring.application.name
          value: product-service
        - name: server.port
          value: "8082"
        - name: spring.datasource.url
          value: jdbc:mysql://mysql-svc:3306/product_ms
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: password
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product-service
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  type: ClusterIP



