apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: haribhuvan/app:user_ms
        # resources:
        #   requests:
        #     cpu: 0.5k
        #     memory: 150Mi
        #   limits:
        #     cpu: 1k
        #     memory: 150Mi
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: spring.application.name
          value: user-service
        - name: server.port
          value: "8081"
        - name: spring.datasource.url
          value: jdbc:mysql://mysql-svc:3306/user_ms
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: password
        ports:
        - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP




